from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class CountryEntry:
    country_name_en: str
    country_name_cn: str
    iso2: str
    iso3: str
    numeric_country_code: str
    world_bank_code: str
    imf_code: str | None = None
    un_code: str | None = None
    common_aliases: tuple[str, ...] = ()

# Global country/economy master based on ISO 3166-1, plus Kosovo (XKX). The list is static so the app does not
# require pycountry/Babel at runtime.  Data-source coverage may vary by economy.
COUNTRY_MASTER = [
    CountryEntry('Bhutan', '不丹', 'BT', 'BTN', '064', 'BTN', 'BTN', '064', ('Kingdom of Bhutan',)),
    CountryEntry('Timor-Leste', '东帝汶', 'TL', 'TLS', '626', 'TLS', 'TLS', '626', ('Democratic Republic of Timor-Leste',)),
    CountryEntry('China', '中国', 'CN', 'CHN', '156', 'CHN', 'CHN', '156', ('PRC', "People's Republic of China", '中华人民共和国')),
    CountryEntry('Taiwan', '中国台湾', 'TW', 'TWN', '158', 'TWN', 'TWN', '158', ('Taiwan, Province of China',)),
    CountryEntry('Macao', '中国澳门特别行政区', 'MO', 'MAC', '446', 'MAC', 'MAC', '446', ('Macao Special Administrative Region of China',)),
    CountryEntry('Hong Kong', '中国香港特别行政区', 'HK', 'HKG', '344', 'HKG', 'HKG', '344', ('Hong Kong Special Administrative Region of China',)),
    CountryEntry('Central African Republic', '中非共和国', 'CF', 'CAF', '140', 'CAF', 'CAF', '140', ()),
    CountryEntry('Denmark', '丹麦', 'DK', 'DNK', '208', 'DNK', 'DNK', '208', ('Kingdom of Denmark',)),
    CountryEntry('Ukraine', '乌克兰', 'UA', 'UKR', '804', 'UKR', 'UKR', '804', ()),
    CountryEntry('Uzbekistan', '乌兹别克斯坦', 'UZ', 'UZB', '860', 'UZB', 'UZB', '860', ('Republic of Uzbekistan',)),
    CountryEntry('Uganda', '乌干达', 'UG', 'UGA', '800', 'UGA', 'UGA', '800', ('Republic of Uganda',)),
    CountryEntry('Uruguay', '乌拉圭', 'UY', 'URY', '858', 'URY', 'URY', '858', ('Eastern Republic of Uruguay',)),
    CountryEntry('Chad', '乍得', 'TD', 'TCD', '148', 'TCD', 'TCD', '148', ('Republic of Chad',)),
    CountryEntry('Yemen', '也门', 'YE', 'YEM', '887', 'YEM', 'YEM', '887', ('Republic of Yemen',)),
    CountryEntry('Armenia', '亚美尼亚', 'AM', 'ARM', '051', 'ARM', 'ARM', '051', ('Republic of Armenia',)),
    CountryEntry('Israel', '以色列', 'IL', 'ISR', '376', 'ISR', 'ISR', '376', ('State of Israel',)),
    CountryEntry('Iraq', '伊拉克', 'IQ', 'IRQ', '368', 'IRQ', 'IRQ', '368', ('Republic of Iraq',)),
    CountryEntry('Iran', '伊朗', 'IR', 'IRN', '364', 'IRN', 'IRN', '364', ('Iran, Islamic Republic of', 'Islamic Republic of Iran')),
    CountryEntry('Belize', '伯利兹', 'BZ', 'BLZ', '084', 'BLZ', 'BLZ', '084', ()),
    CountryEntry('Cape Verde', '佛得角', 'CV', 'CPV', '132', 'CPV', 'CPV', '132', ('Cabo Verde', 'Republic of Cabo Verde')),
    CountryEntry('Russia', '俄罗斯', 'RU', 'RUS', '643', 'RUS', 'RUS', '643', ('Russian Federation',)),
    CountryEntry('Bulgaria', '保加利亚', 'BG', 'BGR', '100', 'BGR', 'BGR', '100', ('Republic of Bulgaria',)),
    CountryEntry('Croatia', '克罗地亚', 'HR', 'HRV', '191', 'HRV', 'HRV', '191', ('Republic of Croatia',)),
    CountryEntry('Guam', '关岛', 'GU', 'GUM', '316', 'GUM', 'GUM', '316', ()),
    CountryEntry('Gambia', '冈比亚', 'GM', 'GMB', '270', 'GMB', 'GMB', '270', ('Republic of the Gambia',)),
    CountryEntry('Iceland', '冰岛', 'IS', 'ISL', '352', 'ISL', 'ISL', '352', ('Republic of Iceland',)),
    CountryEntry('Guinea', '几内亚', 'GN', 'GIN', '324', 'GIN', 'GIN', '324', ('Republic of Guinea',)),
    CountryEntry('Guinea-Bissau', '几内亚比绍', 'GW', 'GNB', '624', 'GNB', 'GNB', '624', ('Republic of Guinea-Bissau',)),
    CountryEntry('Liechtenstein', '列支敦士登', 'LI', 'LIE', '438', 'LIE', 'LIE', '438', ('Principality of Liechtenstein',)),
    CountryEntry('Republic of the Congo', '刚果共和国', 'CG', 'COG', '178', 'COG', 'COG', '178', ('Congo-Brazzaville', 'Congo')),
    CountryEntry('Democratic Republic of the Congo', '刚果民主共和国', 'CD', 'COD', '180', 'COD', 'COD', '180', ('DRC', 'Congo-Kinshasa', 'Congo, The Democratic Republic of the')),
    CountryEntry('Libya', '利比亚', 'LY', 'LBY', '434', 'LBY', 'LBY', '434', ()),
    CountryEntry('Liberia', '利比里亚', 'LR', 'LBR', '430', 'LBR', 'LBR', '430', ('Republic of Liberia',)),
    CountryEntry('Canada', '加拿大', 'CA', 'CAN', '124', 'CAN', 'CAN', '124', ()),
    CountryEntry('Ghana', '加纳', 'GH', 'GHA', '288', 'GHA', 'GHA', '288', ('Republic of Ghana',)),
    CountryEntry('Gabon', '加蓬', 'GA', 'GAB', '266', 'GAB', 'GAB', '266', ('Gabonese Republic',)),
    CountryEntry('Hungary', '匈牙利', 'HU', 'HUN', '348', 'HUN', 'HUN', '348', ()),
    CountryEntry('North Macedonia', '北马其顿', 'MK', 'MKD', '807', 'MKD', 'MKD', '807', ('Republic of North Macedonia',)),
    CountryEntry('Northern Mariana Islands', '北马里亚纳群岛', 'MP', 'MNP', '580', 'MNP', 'MNP', '580', ('Commonwealth of the Northern Mariana Islands',)),
    CountryEntry('South Georgia and the South Sandwich Islands', '南乔治亚和南桑威奇群岛', 'GS', 'SGS', '239', 'SGS', 'SGS', '239', ()),
    CountryEntry('Antarctica', '南极洲', 'AQ', 'ATA', '010', 'ATA', 'ATA', '010', ()),
    CountryEntry('South Sudan', '南苏丹', 'SS', 'SSD', '728', 'SSD', 'SSD', '728', ('Republic of South Sudan',)),
    CountryEntry('South Africa', '南非', 'ZA', 'ZAF', '710', 'ZAF', 'ZAF', '710', ('Republic of South Africa',)),
    CountryEntry('Botswana', '博茨瓦纳', 'BW', 'BWA', '072', 'BWA', 'BWA', '072', ('Republic of Botswana',)),
    CountryEntry('Qatar', '卡塔尔', 'QA', 'QAT', '634', 'QAT', 'QAT', '634', ('State of Qatar',)),
    CountryEntry('Rwanda', '卢旺达', 'RW', 'RWA', '646', 'RWA', 'RWA', '646', ('Rwandese Republic',)),
    CountryEntry('Luxembourg', '卢森堡', 'LU', 'LUX', '442', 'LUX', 'LUX', '442', ('Grand Duchy of Luxembourg',)),
    CountryEntry('India', '印度', 'IN', 'IND', '356', 'IND', 'IND', '356', ('Republic of India',)),
    CountryEntry('Indonesia', '印度尼西亚', 'ID', 'IDN', '360', 'IDN', 'IDN', '360', ('Republic of Indonesia',)),
    CountryEntry('Guatemala', '危地马拉', 'GT', 'GTM', '320', 'GTM', 'GTM', '320', ('Republic of Guatemala',)),
    CountryEntry('Ecuador', '厄瓜多尔', 'EC', 'ECU', '218', 'ECU', 'ECU', '218', ('Republic of Ecuador',)),
    CountryEntry('Eritrea', '厄立特里亚', 'ER', 'ERI', '232', 'ERI', 'ERI', '232', ('the State of Eritrea',)),
    CountryEntry('Syria', '叙利亚', 'SY', 'SYR', '760', 'SYR', 'SYR', '760', ('Syrian Arab Republic',)),
    CountryEntry('Cuba', '古巴', 'CU', 'CUB', '192', 'CUB', 'CUB', '192', ('Republic of Cuba',)),
    CountryEntry('Kyrgyzstan', '吉尔吉斯斯坦', 'KG', 'KGZ', '417', 'KGZ', 'KGZ', '417', ('Kyrgyz Republic',)),
    CountryEntry('Djibouti', '吉布提', 'DJ', 'DJI', '262', 'DJI', 'DJI', '262', ('Republic of Djibouti',)),
    CountryEntry('Kazakhstan', '哈萨克斯坦', 'KZ', 'KAZ', '398', 'KAZ', 'KAZ', '398', ('Republic of Kazakhstan',)),
    CountryEntry('Colombia', '哥伦比亚', 'CO', 'COL', '170', 'COL', 'COL', '170', ('Republic of Colombia',)),
    CountryEntry('Costa Rica', '哥斯达黎加', 'CR', 'CRI', '188', 'CRI', 'CRI', '188', ('Republic of Costa Rica',)),
    CountryEntry('Cameroon', '喀麦隆', 'CM', 'CMR', '120', 'CMR', 'CMR', '120', ('Republic of Cameroon',)),
    CountryEntry('Tuvalu', '图瓦卢', 'TV', 'TUV', '798', 'TUV', 'TUV', '798', ()),
    CountryEntry('Turkmenistan', '土库曼斯坦', 'TM', 'TKM', '795', 'TKM', 'TKM', '795', ()),
    CountryEntry('Turkey', '土耳其', 'TR', 'TUR', '792', 'TUR', 'TUR', '792', ('Türkiye', 'Turkiye', 'Republic of Türkiye')),
    CountryEntry('Saint Lucia', '圣卢西亚', 'LC', 'LCA', '662', 'LCA', 'LCA', '662', ()),
    CountryEntry('Saint Kitts and Nevis', '圣基茨和尼维斯', 'KN', 'KNA', '659', 'KNA', 'KNA', '659', ()),
    CountryEntry('Sao Tome and Principe', '圣多美和普林西比', 'ST', 'STP', '678', 'STP', 'STP', '678', ('Democratic Republic of Sao Tome and Principe',)),
    CountryEntry('Saint Barthélemy', '圣巴泰勒米', 'BL', 'BLM', '652', 'BLM', 'BLM', '652', ()),
    CountryEntry('Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯', 'VC', 'VCT', '670', 'VCT', 'VCT', '670', ()),
    CountryEntry('Saint Pierre and Miquelon', '圣皮埃尔和密克隆群岛', 'PM', 'SPM', '666', 'SPM', 'SPM', '666', ()),
    CountryEntry('Christmas Island', '圣诞岛', 'CX', 'CXR', '162', 'CXR', 'CXR', '162', ()),
    CountryEntry('Saint Helena, Ascension and Tristan da Cunha', '圣赫勒拿', 'SH', 'SHN', '654', 'SHN', 'SHN', '654', ()),
    CountryEntry('San Marino', '圣马力诺', 'SM', 'SMR', '674', 'SMR', 'SMR', '674', ('Republic of San Marino',)),
    CountryEntry('Guyana', '圭亚那', 'GY', 'GUY', '328', 'GUY', 'GUY', '328', ('Republic of Guyana',)),
    CountryEntry('Tanzania', '坦桑尼亚', 'TZ', 'TZA', '834', 'TZA', 'TZA', '834', ('Tanzania, United Republic of', 'United Republic of Tanzania')),
    CountryEntry('Egypt', '埃及', 'EG', 'EGY', '818', 'EGY', 'EGY', '818', ('Arab Republic of Egypt',)),
    CountryEntry('Ethiopia', '埃塞俄比亚', 'ET', 'ETH', '231', 'ETH', 'ETH', '231', ('Federal Democratic Republic of Ethiopia',)),
    CountryEntry('Kiribati', '基里巴斯', 'KI', 'KIR', '296', 'KIR', 'KIR', '296', ('Republic of Kiribati',)),
    CountryEntry('Tajikistan', '塔吉克斯坦', 'TJ', 'TJK', '762', 'TJK', 'TJK', '762', ('Republic of Tajikistan',)),
    CountryEntry('Senegal', '塞内加尔', 'SN', 'SEN', '686', 'SEN', 'SEN', '686', ('Republic of Senegal',)),
    CountryEntry('Serbia', '塞尔维亚', 'RS', 'SRB', '688', 'SRB', 'SRB', '688', ('Republic of Serbia',)),
    CountryEntry('Sierra Leone', '塞拉利昂', 'SL', 'SLE', '694', 'SLE', 'SLE', '694', ('Republic of Sierra Leone',)),
    CountryEntry('Cyprus', '塞浦路斯', 'CY', 'CYP', '196', 'CYP', 'CYP', '196', ('Republic of Cyprus',)),
    CountryEntry('Seychelles', '塞舌尔', 'SC', 'SYC', '690', 'SYC', 'SYC', '690', ('Republic of Seychelles',)),
    CountryEntry('Mexico', '墨西哥', 'MX', 'MEX', '484', 'MEX', 'MEX', '484', ('United Mexican States',)),
    CountryEntry('Togo', '多哥', 'TG', 'TGO', '768', 'TGO', 'TGO', '768', ('Togolese Republic',)),
    CountryEntry('Dominica', '多米尼克', 'DM', 'DMA', '212', 'DMA', 'DMA', '212', ('Commonwealth of Dominica',)),
    CountryEntry('Dominican Republic', '多米尼加共和国', 'DO', 'DOM', '214', 'DOM', 'DOM', '214', ()),
    CountryEntry('Åland Islands', '奥兰群岛', 'AX', 'ALA', '248', 'ALA', 'ALA', '248', ()),
    CountryEntry('Austria', '奥地利', 'AT', 'AUT', '040', 'AUT', 'AUT', '040', ('Republic of Austria',)),
    CountryEntry('Venezuela', '委内瑞拉', 'VE', 'VEN', '862', 'VEN', 'VEN', '862', ('Venezuela, Bolivarian Republic of', 'Bolivarian Republic of Venezuela')),
    CountryEntry('Bangladesh', '孟加拉国', 'BD', 'BGD', '050', 'BGD', 'BGD', '050', ("People's Republic of Bangladesh",)),
    CountryEntry('Angola', '安哥拉', 'AO', 'AGO', '024', 'AGO', 'AGO', '024', ('Republic of Angola',)),
    CountryEntry('Anguilla', '安圭拉', 'AI', 'AIA', '660', 'AIA', 'AIA', '660', ()),
    CountryEntry('Antigua and Barbuda', '安提瓜和巴布达', 'AG', 'ATG', '028', 'ATG', 'ATG', '028', ()),
    CountryEntry('Andorra', '安道尔', 'AD', 'AND', '020', 'AND', 'AND', '020', ('Principality of Andorra',)),
    CountryEntry('Micronesia', '密克罗尼西亚', 'FM', 'FSM', '583', 'FSM', 'FSM', '583', ('Micronesia, Federated States of', 'Federated States of Micronesia')),
    CountryEntry('Nicaragua', '尼加拉瓜', 'NI', 'NIC', '558', 'NIC', 'NIC', '558', ('Republic of Nicaragua',)),
    CountryEntry('Nigeria', '尼日利亚', 'NG', 'NGA', '566', 'NGA', 'NGA', '566', ('Federal Republic of Nigeria',)),
    CountryEntry('Niger', '尼日尔', 'NE', 'NER', '562', 'NER', 'NER', '562', ('Republic of the Niger',)),
    CountryEntry('Nepal', '尼泊尔', 'NP', 'NPL', '524', 'NPL', 'NPL', '524', ('Federal Democratic Republic of Nepal',)),
    CountryEntry('Palestine', '巴勒斯坦', 'PS', 'PSE', '275', 'PSE', 'PSE', '275', ('State of Palestine', 'Palestinian Territories', 'the State of Palestine', 'Palestine, State of')),
    CountryEntry('Bahamas', '巴哈马', 'BS', 'BHS', '044', 'BHS', 'BHS', '044', ('Commonwealth of the Bahamas',)),
    CountryEntry('Pakistan', '巴基斯坦', 'PK', 'PAK', '586', 'PAK', 'PAK', '586', ('Islamic Republic of Pakistan',)),
    CountryEntry('Barbados', '巴巴多斯', 'BB', 'BRB', '052', 'BRB', 'BRB', '052', ()),
    CountryEntry('Papua New Guinea', '巴布亚新几内亚', 'PG', 'PNG', '598', 'PNG', 'PNG', '598', ('Independent State of Papua New Guinea',)),
    CountryEntry('Paraguay', '巴拉圭', 'PY', 'PRY', '600', 'PRY', 'PRY', '600', ('Republic of Paraguay',)),
    CountryEntry('Panama', '巴拿马', 'PA', 'PAN', '591', 'PAN', 'PAN', '591', ('Republic of Panama',)),
    CountryEntry('Bahrain', '巴林', 'BH', 'BHR', '048', 'BHR', 'BHR', '048', ('Kingdom of Bahrain',)),
    CountryEntry('Brazil', '巴西', 'BR', 'BRA', '076', 'BRA', 'BRA', '076', ('Federative Republic of Brazil',)),
    CountryEntry('Burkina Faso', '布基纳法索', 'BF', 'BFA', '854', 'BFA', 'BFA', '854', ()),
    CountryEntry('Burundi', '布隆迪', 'BI', 'BDI', '108', 'BDI', 'BDI', '108', ('Republic of Burundi',)),
    CountryEntry('Bouvet Island', '布韦岛', 'BV', 'BVT', '074', 'BVT', 'BVT', '074', ()),
    CountryEntry('Greece', '希腊', 'GR', 'GRC', '300', 'GRC', 'GRC', '300', ('Hellenic Republic',)),
    CountryEntry('Palau', '帕劳', 'PW', 'PLW', '585', 'PLW', 'PLW', '585', ('Republic of Palau',)),
    CountryEntry('Cook Islands', '库克群岛', 'CK', 'COK', '184', 'COK', 'COK', '184', ()),
    CountryEntry('Curaçao', '库拉索', 'CW', 'CUW', '531', 'CUW', 'CUW', '531', ()),
    CountryEntry('Cayman Islands', '开曼群岛', 'KY', 'CYM', '136', 'CYM', 'CYM', '136', ()),
    CountryEntry('Germany', '德国', 'DE', 'DEU', '276', 'DEU', 'DEU', '276', ('Federal Republic of Germany',)),
    CountryEntry('Italy', '意大利', 'IT', 'ITA', '380', 'ITA', 'ITA', '380', ('Italian Republic',)),
    CountryEntry('Solomon Islands', '所罗门群岛', 'SB', 'SLB', '090', 'SLB', 'SLB', '090', ()),
    CountryEntry('Tokelau', '托克劳', 'TK', 'TKL', '772', 'TKL', 'TKL', '772', ()),
    CountryEntry('Latvia', '拉脱维亚', 'LV', 'LVA', '428', 'LVA', 'LVA', '428', ('Republic of Latvia',)),
    CountryEntry('Norway', '挪威', 'NO', 'NOR', '578', 'NOR', 'NOR', '578', ('Kingdom of Norway',)),
    CountryEntry('Czech Republic', '捷克', 'CZ', 'CZE', '203', 'CZE', 'CZE', '203', ('Czechia',)),
    CountryEntry('Moldova', '摩尔多瓦', 'MD', 'MDA', '498', 'MDA', 'MDA', '498', ('Moldova, Republic of', 'Republic of Moldova')),
    CountryEntry('Morocco', '摩洛哥', 'MA', 'MAR', '504', 'MAR', 'MAR', '504', ('Kingdom of Morocco',)),
    CountryEntry('Monaco', '摩纳哥', 'MC', 'MCO', '492', 'MCO', 'MCO', '492', ('Principality of Monaco',)),
    CountryEntry('Brunei', '文莱', 'BN', 'BRN', '096', 'BRN', 'BRN', '096', ('Brunei Darussalam',)),
    CountryEntry('Fiji', '斐济', 'FJ', 'FJI', '242', 'FJI', 'FJI', '242', ('Republic of Fiji',)),
    CountryEntry('Eswatini', '斯威士兰（埃斯瓦蒂尼）', 'SZ', 'SWZ', '748', 'SWZ', 'SWZ', '748', ('Swaziland', 'Kingdom of Eswatini')),
    CountryEntry('Slovakia', '斯洛伐克', 'SK', 'SVK', '703', 'SVK', 'SVK', '703', ('Slovak Republic',)),
    CountryEntry('Slovenia', '斯洛文尼亚', 'SI', 'SVN', '705', 'SVN', 'SVN', '705', ('Republic of Slovenia',)),
    CountryEntry('Svalbard and Jan Mayen', '斯瓦尔巴和扬马延', 'SJ', 'SJM', '744', 'SJM', 'SJM', '744', ()),
    CountryEntry('Sri Lanka', '斯里兰卡', 'LK', 'LKA', '144', 'LKA', 'LKA', '144', ('Democratic Socialist Republic of Sri Lanka',)),
    CountryEntry('Singapore', '新加坡', 'SG', 'SGP', '702', 'SGP', 'SGP', '702', ('Republic of Singapore',)),
    CountryEntry('New Caledonia', '新喀里多尼亚', 'NC', 'NCL', '540', 'NCL', 'NCL', '540', ()),
    CountryEntry('New Zealand', '新西兰', 'NZ', 'NZL', '554', 'NZL', 'NZL', '554', ()),
    CountryEntry('Japan', '日本', 'JP', 'JPN', '392', 'JPN', 'JPN', '392', ()),
    CountryEntry('Chile', '智利', 'CL', 'CHL', '152', 'CHL', 'CHL', '152', ('Republic of Chile',)),
    CountryEntry('North Korea', '朝鲜', 'KP', 'PRK', '408', 'PRK', 'PRK', '408', ("Democratic People's Republic of Korea", 'DPRK', 'Korea, North', "Korea, Democratic People's Republic of")),
    CountryEntry('Cambodia', '柬埔寨', 'KH', 'KHM', '116', 'KHM', 'KHM', '116', ('Kingdom of Cambodia',)),
    CountryEntry('Guernsey', '根西岛', 'GG', 'GGY', '831', 'GGY', 'GGY', '831', ()),
    CountryEntry('Grenada', '格林纳达', 'GD', 'GRD', '308', 'GRD', 'GRD', '308', ()),
    CountryEntry('Greenland', '格陵兰', 'GL', 'GRL', '304', 'GRL', 'GRL', '304', ()),
    CountryEntry('Georgia', '格鲁吉亚', 'GE', 'GEO', '268', 'GEO', 'GEO', '268', ()),
    CountryEntry('Vatican City', '梵蒂冈', 'VA', 'VAT', '336', 'VAT', 'VAT', '336', ('Holy See', 'Holy See (Vatican City State)')),
    CountryEntry('Belgium', '比利时', 'BE', 'BEL', '056', 'BEL', 'BEL', '056', ('Kingdom of Belgium',)),
    CountryEntry('Mauritania', '毛里塔尼亚', 'MR', 'MRT', '478', 'MRT', 'MRT', '478', ('Islamic Republic of Mauritania',)),
    CountryEntry('Mauritius', '毛里求斯', 'MU', 'MUS', '480', 'MUS', 'MUS', '480', ('Republic of Mauritius',)),
    CountryEntry('Tonga', '汤加', 'TO', 'TON', '776', 'TON', 'TON', '776', ('Kingdom of Tonga',)),
    CountryEntry('Saudi Arabia', '沙特阿拉伯', 'SA', 'SAU', '682', 'SAU', 'SAU', '682', ('Kingdom of Saudi Arabia',)),
    CountryEntry('France', '法国', 'FR', 'FRA', '250', 'FRA', 'FRA', '250', ('French Republic',)),
    CountryEntry('French Southern Territories', '法属南部领地', 'TF', 'ATF', '260', 'ATF', 'ATF', '260', ()),
    CountryEntry('Saint Martin (French part)', '法属圣马丁', 'MF', 'MAF', '663', 'MAF', 'MAF', '663', ()),
    CountryEntry('French Guiana', '法属圭亚那', 'GF', 'GUF', '254', 'GUF', 'GUF', '254', ()),
    CountryEntry('French Polynesia', '法属波利尼西亚', 'PF', 'PYF', '258', 'PYF', 'PYF', '258', ()),
    CountryEntry('Faroe Islands', '法罗群岛', 'FO', 'FRO', '234', 'FRO', 'FRO', '234', ()),
    CountryEntry('Poland', '波兰', 'PL', 'POL', '616', 'POL', 'POL', '616', ('Republic of Poland',)),
    CountryEntry('Puerto Rico', '波多黎各', 'PR', 'PRI', '630', 'PRI', 'PRI', '630', ()),
    CountryEntry('Bosnia and Herzegovina', '波斯尼亚和黑塞哥维那', 'BA', 'BIH', '070', 'BIH', 'BIH', '070', ('Republic of Bosnia and Herzegovina',)),
    CountryEntry('Thailand', '泰国', 'TH', 'THA', '764', 'THA', 'THA', '764', ('Kingdom of Thailand',)),
    CountryEntry('Jersey', '泽西岛', 'JE', 'JEY', '832', 'JEY', 'JEY', '832', ()),
    CountryEntry('Zimbabwe', '津巴布韦', 'ZW', 'ZWE', '716', 'ZWE', 'ZWE', '716', ('Republic of Zimbabwe',)),
    CountryEntry('Honduras', '洪都拉斯', 'HN', 'HND', '340', 'HND', 'HND', '340', ('Republic of Honduras',)),
    CountryEntry('Haiti', '海地', 'HT', 'HTI', '332', 'HTI', 'HTI', '332', ('Republic of Haiti',)),
    CountryEntry('Australia', '澳大利亚', 'AU', 'AUS', '036', 'AUS', 'AUS', '036', ()),
    CountryEntry('Ireland', '爱尔兰', 'IE', 'IRL', '372', 'IRL', 'IRL', '372', ()),
    CountryEntry('Estonia', '爱沙尼亚', 'EE', 'EST', '233', 'EST', 'EST', '233', ('Republic of Estonia',)),
    CountryEntry('Jamaica', '牙买加', 'JM', 'JAM', '388', 'JAM', 'JAM', '388', ()),
    CountryEntry('Turks and Caicos Islands', '特克斯和凯科斯群岛', 'TC', 'TCA', '796', 'TCA', 'TCA', '796', ()),
    CountryEntry('Trinidad and Tobago', '特立尼达和多巴哥', 'TT', 'TTO', '780', 'TTO', 'TTO', '780', ('Republic of Trinidad and Tobago',)),
    CountryEntry('Bolivia', '玻利维亚', 'BO', 'BOL', '068', 'BOL', 'BOL', '068', ('Bolivia, Plurinational State of', 'Plurinational State of Bolivia')),
    CountryEntry('Nauru', '瑙鲁', 'NR', 'NRU', '520', 'NRU', 'NRU', '520', ('Republic of Nauru',)),
    CountryEntry('Sweden', '瑞典', 'SE', 'SWE', '752', 'SWE', 'SWE', '752', ('Kingdom of Sweden',)),
    CountryEntry('Switzerland', '瑞士', 'CH', 'CHE', '756', 'CHE', 'CHE', '756', ('Swiss Confederation',)),
    CountryEntry('Guadeloupe', '瓜德罗普', 'GP', 'GLP', '312', 'GLP', 'GLP', '312', ()),
    CountryEntry('Wallis and Futuna', '瓦利斯和富图纳', 'WF', 'WLF', '876', 'WLF', 'WLF', '876', ()),
    CountryEntry('Vanuatu', '瓦努阿图', 'VU', 'VUT', '548', 'VUT', 'VUT', '548', ('Republic of Vanuatu',)),
    CountryEntry('Réunion', '留尼汪', 'RE', 'REU', '638', 'REU', 'REU', '638', ()),
    CountryEntry('Belarus', '白俄罗斯', 'BY', 'BLR', '112', 'BLR', 'BLR', '112', ('Republic of Belarus',)),
    CountryEntry('Bermuda', '百慕大', 'BM', 'BMU', '060', 'BMU', 'BMU', '060', ()),
    CountryEntry('Pitcairn', '皮特凯恩群岛', 'PN', 'PCN', '612', 'PCN', 'PCN', '612', ()),
    CountryEntry('Gibraltar', '直布罗陀', 'GI', 'GIB', '292', 'GIB', 'GIB', '292', ()),
    CountryEntry('Falkland Islands (Malvinas)', '福克兰群岛', 'FK', 'FLK', '238', 'FLK', 'FLK', '238', ()),
    CountryEntry('Kuwait', '科威特', 'KW', 'KWT', '414', 'KWT', 'KWT', '414', ('State of Kuwait',)),
    CountryEntry('Comoros', '科摩罗', 'KM', 'COM', '174', 'COM', 'COM', '174', ('Union of the Comoros',)),
    CountryEntry("Côte d'Ivoire", '科特迪瓦', 'CI', 'CIV', '384', 'CIV', 'CIV', '384', ('Ivory Coast', "Republic of Côte d'Ivoire")),
    CountryEntry('Cocos (Keeling) Islands', '科科斯（基林）群岛', 'CC', 'CCK', '166', 'CCK', 'CCK', '166', ()),
    CountryEntry('Peru', '秘鲁', 'PE', 'PER', '604', 'PER', 'PER', '604', ('Republic of Peru',)),
    CountryEntry('Tunisia', '突尼斯', 'TN', 'TUN', '788', 'TUN', 'TUN', '788', ('Republic of Tunisia',)),
    CountryEntry('Lithuania', '立陶宛', 'LT', 'LTU', '440', 'LTU', 'LTU', '440', ('Republic of Lithuania',)),
    CountryEntry('Somalia', '索马里', 'SO', 'SOM', '706', 'SOM', 'SOM', '706', ('Federal Republic of Somalia',)),
    CountryEntry('Jordan', '约旦', 'JO', 'JOR', '400', 'JOR', 'JOR', '400', ('Hashemite Kingdom of Jordan',)),
    CountryEntry('Namibia', '纳米比亚', 'NA', 'NAM', '516', 'NAM', 'NAM', '516', ('Republic of Namibia',)),
    CountryEntry('Niue', '纽埃', 'NU', 'NIU', '570', 'NIU', 'NIU', '570', ()),
    CountryEntry('Myanmar', '缅甸', 'MM', 'MMR', '104', 'MMR', 'MMR', '104', ('Burma', 'Republic of Myanmar')),
    CountryEntry('Romania', '罗马尼亚', 'RO', 'ROU', '642', 'ROU', 'ROU', '642', ()),
    CountryEntry('United States', '美国', 'US', 'USA', '840', 'USA', 'USA', '840', ('US', 'USA', 'United States of America', '美利坚合众国')),
    CountryEntry('United States Minor Outlying Islands', '美国本土外小岛屿', 'UM', 'UMI', '581', 'UMI', 'UMI', '581', ()),
    CountryEntry('Virgin Islands, U.S.', '美属维尔京群岛', 'VI', 'VIR', '850', 'VIR', 'VIR', '850', ('Virgin Islands of the United States',)),
    CountryEntry('American Samoa', '美属萨摩亚', 'AS', 'ASM', '016', 'ASM', 'ASM', '016', ()),
    CountryEntry('Laos', '老挝', 'LA', 'LAO', '418', 'LAO', 'LAO', '418', ('Lao PDR', "Lao People's Democratic Republic")),
    CountryEntry('Kenya', '肯尼亚', 'KE', 'KEN', '404', 'KEN', 'KEN', '404', ('Republic of Kenya',)),
    CountryEntry('Finland', '芬兰', 'FI', 'FIN', '246', 'FIN', 'FIN', '246', ('Republic of Finland',)),
    CountryEntry('Sudan', '苏丹', 'SD', 'SDN', '729', 'SDN', 'SDN', '729', ('Republic of the Sudan',)),
    CountryEntry('Suriname', '苏里南', 'SR', 'SUR', '740', 'SUR', 'SUR', '740', ('Republic of Suriname',)),
    CountryEntry('United Kingdom', '英国', 'GB', 'GBR', '826', 'GBR', 'GBR', '826', ('UK', 'Britain', 'Great Britain', 'United Kingdom of Great Britain and Northern Ireland')),
    CountryEntry('British Indian Ocean Territory', '英属印度洋领地', 'IO', 'IOT', '086', 'IOT', 'IOT', '086', ()),
    CountryEntry('Virgin Islands, British', '英属维尔京群岛', 'VG', 'VGB', '092', 'VGB', 'VGB', '092', ('British Virgin Islands',)),
    CountryEntry('Netherlands', '荷兰', 'NL', 'NLD', '528', 'NLD', 'NLD', '528', ('Kingdom of the Netherlands',)),
    CountryEntry('Bonaire, Sint Eustatius and Saba', '荷属加勒比区', 'BQ', 'BES', '535', 'BES', 'BES', '535', ()),
    CountryEntry('Sint Maarten (Dutch part)', '荷属圣马丁', 'SX', 'SXM', '534', 'SXM', 'SXM', '534', ()),
    CountryEntry('Mozambique', '莫桑比克', 'MZ', 'MOZ', '508', 'MOZ', 'MOZ', '508', ('Republic of Mozambique',)),
    CountryEntry('Lesotho', '莱索托', 'LS', 'LSO', '426', 'LSO', 'LSO', '426', ('Kingdom of Lesotho',)),
    CountryEntry('Philippines', '菲律宾', 'PH', 'PHL', '608', 'PHL', 'PHL', '608', ('Republic of the Philippines',)),
    CountryEntry('El Salvador', '萨尔瓦多', 'SV', 'SLV', '222', 'SLV', 'SLV', '222', ('Republic of El Salvador',)),
    CountryEntry('Samoa', '萨摩亚', 'WS', 'WSM', '882', 'WSM', 'WSM', '882', ('Independent State of Samoa',)),
    CountryEntry('Portugal', '葡萄牙', 'PT', 'PRT', '620', 'PRT', 'PRT', '620', ('Portuguese Republic',)),
    CountryEntry('Mongolia', '蒙古', 'MN', 'MNG', '496', 'MNG', 'MNG', '496', ()),
    CountryEntry('Montserrat', '蒙特塞拉特', 'MS', 'MSR', '500', 'MSR', 'MSR', '500', ()),
    CountryEntry('Western Sahara', '西撒哈拉', 'EH', 'ESH', '732', 'ESH', 'ESH', '732', ()),
    CountryEntry('Spain', '西班牙', 'ES', 'ESP', '724', 'ESP', 'ESP', '724', ('Kingdom of Spain',)),
    CountryEntry('Norfolk Island', '诺福克岛', 'NF', 'NFK', '574', 'NFK', 'NFK', '574', ()),
    CountryEntry('Benin', '贝宁', 'BJ', 'BEN', '204', 'BEN', 'BEN', '204', ('Republic of Benin',)),
    CountryEntry('Zambia', '赞比亚', 'ZM', 'ZMB', '894', 'ZMB', 'ZMB', '894', ('Republic of Zambia',)),
    CountryEntry('Equatorial Guinea', '赤道几内亚', 'GQ', 'GNQ', '226', 'GNQ', 'GNQ', '226', ('Republic of Equatorial Guinea',)),
    CountryEntry('Heard Island and McDonald Islands', '赫德岛和麦克唐纳群岛', 'HM', 'HMD', '334', 'HMD', 'HMD', '334', ()),
    CountryEntry('Vietnam', '越南', 'VN', 'VNM', '704', 'VNM', 'VNM', '704', ('Viet Nam', 'Socialist Republic of Viet Nam')),
    CountryEntry('Azerbaijan', '阿塞拜疆', 'AZ', 'AZE', '031', 'AZE', 'AZE', '031', ('Republic of Azerbaijan',)),
    CountryEntry('Afghanistan', '阿富汗', 'AF', 'AFG', '004', 'AFG', 'AFG', '004', ('Islamic Republic of Afghanistan',)),
    CountryEntry('Algeria', '阿尔及利亚', 'DZ', 'DZA', '012', 'DZA', 'DZA', '012', ("People's Democratic Republic of Algeria",)),
    CountryEntry('Albania', '阿尔巴尼亚', 'AL', 'ALB', '008', 'ALB', 'ALB', '008', ('Republic of Albania',)),
    CountryEntry('United Arab Emirates', '阿拉伯联合酋长国', 'AE', 'ARE', '784', 'ARE', 'ARE', '784', ('UAE',)),
    CountryEntry('Oman', '阿曼', 'OM', 'OMN', '512', 'OMN', 'OMN', '512', ('Sultanate of Oman',)),
    CountryEntry('Argentina', '阿根廷', 'AR', 'ARG', '032', 'ARG', 'ARG', '032', ('Argentine Republic',)),
    CountryEntry('Aruba', '阿鲁巴', 'AW', 'ABW', '533', 'ABW', 'ABW', '533', ()),
    CountryEntry('South Korea', '韩国', 'KR', 'KOR', '410', 'KOR', 'KOR', '410', ('Republic of Korea', 'Korea, South', 'Korea, Republic of')),
    CountryEntry('Maldives', '马尔代夫', 'MV', 'MDV', '462', 'MDV', 'MDV', '462', ('Republic of Maldives',)),
    CountryEntry('Isle of Man', '马恩岛', 'IM', 'IMN', '833', 'IMN', 'IMN', '833', ()),
    CountryEntry('Malawi', '马拉维', 'MW', 'MWI', '454', 'MWI', 'MWI', '454', ('Republic of Malawi',)),
    CountryEntry('Martinique', '马提尼克', 'MQ', 'MTQ', '474', 'MTQ', 'MTQ', '474', ()),
    CountryEntry('Malaysia', '马来西亚', 'MY', 'MYS', '458', 'MYS', 'MYS', '458', ()),
    CountryEntry('Mayotte', '马约特', 'YT', 'MYT', '175', 'MYT', 'MYT', '175', ()),
    CountryEntry('Marshall Islands', '马绍尔群岛', 'MH', 'MHL', '584', 'MHL', 'MHL', '584', ('Republic of the Marshall Islands',)),
    CountryEntry('Malta', '马耳他', 'MT', 'MLT', '470', 'MLT', 'MLT', '470', ('Republic of Malta',)),
    CountryEntry('Madagascar', '马达加斯加', 'MG', 'MDG', '450', 'MDG', 'MDG', '450', ('Republic of Madagascar',)),
    CountryEntry('Mali', '马里', 'ML', 'MLI', '466', 'MLI', 'MLI', '466', ('Republic of Mali',)),
    CountryEntry('Lebanon', '黎巴嫩', 'LB', 'LBN', '422', 'LBN', 'LBN', '422', ('Lebanese Republic',)),
    CountryEntry('Montenegro', '黑山', 'ME', 'MNE', '499', 'MNE', 'MNE', '499', ()),
    CountryEntry('Kosovo', '科索沃', 'XK', 'XKX', '383', 'XKX', 'UVK', '383', ('Republic of Kosovo',)),
]

COUNTRY_BY_ISO3 = {entry.iso3: entry for entry in COUNTRY_MASTER}
COUNTRY_BY_ISO2 = {entry.iso2: entry for entry in COUNTRY_MASTER}

def country_display_name(entry: CountryEntry) -> str:
    return f"{entry.country_name_cn}（{entry.country_name_en}）"

def _norm(value: str) -> str:
    return " ".join((value or "").strip().casefold().replace("（", "(").replace("）", ")").split())

_COUNTRY_LOOKUP: dict[str, CountryEntry] = {}
for _entry in COUNTRY_MASTER:
    _keys = {_entry.iso2, _entry.iso3, _entry.country_name_en, _entry.country_name_cn, country_display_name(_entry), f"{_entry.country_name_cn} ({_entry.country_name_en})", *_entry.common_aliases}
    for _key in _keys:
        if _key:
            _COUNTRY_LOOKUP[_norm(_key)] = _entry

def lookup_country(country_code_or_name: str) -> CountryEntry | None:
    """Resolve ISO2/ISO3, Chinese/English name, display label, or common alias."""
    return _COUNTRY_LOOKUP.get(_norm(country_code_or_name))

def normalize_country_code(country_code_or_name: str) -> str | None:
    entry = lookup_country(country_code_or_name)
    return entry.iso3 if entry else None

def all_country_display_names() -> list[str]:
    """Return Chinese-first bilingual labels for the global country/economy dropdown."""
    return sorted((country_display_name(entry) for entry in COUNTRY_MASTER), key=str.casefold)

def lookup_by_display_name(display_name: str) -> CountryEntry | None:
    return lookup_country(display_name)
